#!/usr/bin/env python3
"""Verilator + Python behavioural cosim harness for the Embedded
Coder SV emit.

For one fixture:

  1. `matlabc -emit-sv  <mflow> --subsystem <name>`  -> SV DUT
  2. `matlabc -emit-python <mflow> --subsystem <name>` -> Python ref
  3. Parse the SV module's port list, generate a C++ testbench that
     reads Q16.16-encoded inputs from stdin and writes per-tick
     outputs to stdout.
  4. Build it with `verilator --cc --exe --build`.
  5. Drive a deterministic input stimulus through BOTH the SV (via
     the Verilator binary) and the Python class wrapper. Compare
     per-tick outputs with tolerance `--tol`.

The Python emit uses f64; the SV emit uses Q16.16 fi.  Both run the
same difference equation, so the divergence comes from coefficient
rounding (e.g. `fi(0.05, 1, 32, 16)` → int32 3276 → 0.04999542...)
and from intermediate truncation in fi-multiply chains. `--tol`
absorbs that quantisation noise.

Skips cleanly (exit 0 + warning) when verilator isn't on PATH so
the surrounding CTest lane is safe to enable everywhere.

Usage:
  cosim.py <matlabc> <fixture.mflow> <subsystem> \
      [--ticks N] [--tol T] [--stimulus step|step_first|step_second]
"""
from __future__ import annotations
import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def parse_sv_ports(sv_text: str):
    """Walk the module declaration and pull out (name, width) lists
    for the user-visible data inputs and outputs.  Tracks whether
    the module is sequential (clk + rst_n present) or pure
    combinational (no clock ports — common for stateless mixers /
    comparators / threshold switches). The control ports (clk,
    rst_n, reset) are wiggled by the testbench directly when present
    and skipped otherwise."""
    m = re.search(r"module\s+(\w+)\s*\((.*?)\);", sv_text, re.DOTALL)
    if not m:
        raise ValueError("no module declaration found")
    mod_name = m.group(1)
    body = m.group(2)
    ins = []
    outs = []
    has_clk = False
    has_rst_n = False
    has_reset = False
    for line in body.split(","):
        line = line.strip()
        if not line:
            continue
        is_in  = line.startswith("input")
        is_out = line.startswith("output")
        if not (is_in or is_out):
            continue
        # Vector ports: `[H:L]` brackets present.
        bracket = re.search(r"\[(\d+):", line)
        # Port name = last whitespace-separated token.
        port = line.split()[-1]
        width = (int(bracket.group(1)) + 1) if bracket else 1
        if is_in:
            if port == "clk":
                has_clk = True
                continue
            if port == "rst_n":
                has_rst_n = True
                continue
            if port == "reset":
                has_reset = True
                continue
            ins.append((port, width))
        else:
            outs.append((port, width))
    return mod_name, ins, outs, has_clk, has_rst_n, has_reset


def gen_testbench(mod_name: str, ins, outs, has_clk: bool,
                  has_rst_n: bool, has_reset: bool) -> str:
    """C++ testbench that reads Q16.16 stimulus from stdin and
    prints captured outputs to stdout, one CSV line per tick. Adapts
    to combinational vs sequential modules — only drives clk/rst_n/
    reset when the module declares those ports."""
    inputs_reset = "\n".join(f"    dut->{n} = 0;" for n, _ in ins)
    inputs_drive = "\n".join(
        f"        dut->{n} = vals[{i}];" for i, (n, _) in enumerate(ins))
    output_args  = ", ".join(f"(int32_t)dut->{n}" for n, _ in outs)
    output_fmt   = ",".join(["%d"] * len(outs)) + "\\n"

    if has_clk and has_rst_n:
        # Sequential module: hold reset for two cycles, then drive
        # the per-tick stimulus around posedge-clk transitions.
        reset_block = "    dut->clk = 0;\n    dut->rst_n = 0;\n"
        if has_reset:
            reset_block += "    dut->reset = 1;\n"
        reset_block += inputs_reset + "\n"
        reset_block += "    dut->eval();\n"
        reset_block += "    for (int i = 0; i < 2; ++i) { "
        reset_block += "dut->clk = 1; dut->eval(); "
        reset_block += "dut->clk = 0; dut->eval(); }\n"
        reset_block += "    dut->rst_n = 1;\n"
        if has_reset:
            reset_block += "    dut->reset = 0;\n"
        reset_block += "    dut->eval();\n"
        tick_pre   = "        dut->clk = 0; dut->eval();\n"
        tick_post  = "        dut->clk = 1; dut->eval();\n"
    else:
        # Pure combinational module — no clock to wiggle. Every tick
        # is a fresh `eval()` after the new inputs are driven.
        reset_block = inputs_reset + "\n    dut->eval();\n"
        tick_pre   = "        dut->eval();\n"
        tick_post  = ""
    return f"""// Generated by cosim.py.  Do not edit.
#include "V{mod_name}.h"
#include "verilated.h"
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

int main(int argc, char** argv) {{
    Verilated::commandArgs(argc, argv);
    V{mod_name}* dut = new V{mod_name};

{reset_block}
    char line[2048];
    while (fgets(line, sizeof(line), stdin)) {{
        int32_t vals[32] = {{0}};
        int n = 0;
        char* tok = strtok(line, ",\\n");
        while (tok && n < 32) {{
            vals[n++] = (int32_t)strtoll(tok, NULL, 10);
            tok = strtok(NULL, ",\\n");
        }}
{inputs_drive}
{tick_pre}        printf("{output_fmt}", {output_args});
        fflush(stdout);
{tick_post}    }}

    delete dut;
    return 0;
}}
"""


def fi_encode(v: float, frac: int = 16) -> int:
    return int(round(v * (1 << frac)))


def fi_decode(v: int, frac: int = 16) -> float:
    return v / (1 << frac)


def stimulus_seq(kind: str, n_inputs: int, n_ticks: int):
    """Pre-baked input sequences.  Keep them simple so the tolerance
    stays predictable.  Real cosim suites can pass arbitrary
    stimulus via --stimulus=file:<path>."""
    if kind == "step":
        return [(1.0,) * n_inputs for _ in range(n_ticks)]
    if kind == "step_first":
        return [((1.0,) + (0.0,) * (n_inputs - 1)) for _ in range(n_ticks)]
    if kind == "step_second":
        if n_inputs < 2:
            return stimulus_seq("step", n_inputs, n_ticks)
        return [((0.0, 1.0) + (0.0,) * (n_inputs - 2))
                for _ in range(n_ticks)]
    raise ValueError(f"unknown stimulus kind: {kind}")


def python_classname(emit_text: str, fallback: str) -> str:
    """Pull the auto-generated `class Foo:` name straight out of
    the Python emit so we don't have to mirror the C++
    `toCamelCase` rules."""
    m = re.search(r"^class\s+(\w+)\s*:", emit_text, re.MULTILINE)
    return m.group(1) if m else fallback


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("matlabc")
    ap.add_argument("mflow")
    ap.add_argument("subsystem")
    ap.add_argument("--ticks", type=int, default=50)
    ap.add_argument("--tol", type=float, default=0.02)
    ap.add_argument("--stimulus", default="step")
    args = ap.parse_args()

    if not shutil.which("verilator"):
        print("skip: verilator not on PATH", file=sys.stderr)
        return 0

    sv_text = subprocess.check_output(
        [args.matlabc, "-emit-sv", args.mflow,
         "--subsystem", args.subsystem]).decode()
    py_text = subprocess.check_output(
        [args.matlabc, "-emit-python", args.mflow,
         "--subsystem", args.subsystem]).decode()

    (mod_name, ins, outs,
     has_clk, has_rst_n, has_reset) = parse_sv_ports(sv_text)
    if not ins or not outs:
        print(f"skip {args.subsystem}: empty port list", file=sys.stderr)
        return 0

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        sv_file = td / f"{mod_name}.sv"
        py_file = td / f"{args.subsystem}.py"
        tb_file = td / "tb.cpp"
        sv_file.write_text(sv_text)
        py_file.write_text(py_text)
        tb_file.write_text(gen_testbench(mod_name, ins, outs,
                                          has_clk, has_rst_n,
                                          has_reset))

        verilator_cmd = [
            "verilator", "--cc", str(sv_file),
            "--exe", str(tb_file), "--build",
            # Suppress the cosmetic warnings the lint lane already
            # explicitly accepts as benign.
            "-Wno-WIDTHEXPAND", "-Wno-WIDTHTRUNC",
            "-Wno-UNUSED", "-Wno-DECLFILENAME",
            "-Wno-ALWCOMBORDER", "-Wno-UNOPTFLAT",
            "-CFLAGS", "-O1", "-j", "4",
        ]
        try:
            subprocess.run(verilator_cmd, cwd=td, check=True,
                           stdout=subprocess.DEVNULL,
                           stderr=subprocess.PIPE)
        except subprocess.CalledProcessError as e:
            print(f"{args.subsystem}: verilator build failed", file=sys.stderr)
            sys.stderr.buffer.write(e.stderr or b"")
            return 1

        inputs = stimulus_seq(args.stimulus, len(ins), args.ticks)
        sv_stdin = "\n".join(
            ",".join(str(fi_encode(v)) for v in tick)
            for tick in inputs) + "\n"

        bin_path = td / "obj_dir" / f"V{mod_name}"
        sv_run = subprocess.run([str(bin_path)],
                                input=sv_stdin.encode(),
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE,
                                check=True)
        sv_outputs = []
        for line in sv_run.stdout.decode().strip().split("\n"):
            if not line:
                continue
            raw = [int(v) for v in line.split(",")]
            decoded = []
            for v, (_, w) in zip(raw, outs):
                # 1-bit output → boolean (0 or 1); wider outputs are
                # Q16.16 fi values that we scale back to float.
                if w == 1:
                    decoded.append(bool(v))
                else:
                    decoded.append(fi_decode(v))
            sv_outputs.append(decoded)

        # Python reference.
        spec = importlib.util.spec_from_file_location(args.subsystem, py_file)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        cls_name = python_classname(py_text, args.subsystem)
        plant = getattr(mod, cls_name)()
        py_outputs = []
        for tick in inputs:
            res = plant.step(*tick)
            if isinstance(res, tuple):
                py_outputs.append(list(res))
            else:
                py_outputs.append([res])

        # Compare. Booleans must match exactly; floats are compared
        # with the configured tolerance.
        worst = 0.0
        failures = 0
        for t, (sv_row, py_row) in enumerate(zip(sv_outputs, py_outputs)):
            for i, (sv_v, py_v) in enumerate(zip(sv_row, py_row)):
                if isinstance(sv_v, bool) or isinstance(py_v, bool):
                    ok = bool(sv_v) == bool(py_v)
                    err = 0.0 if ok else 1.0
                else:
                    err = abs(sv_v - py_v)
                    ok  = err <= args.tol
                if err > worst:
                    worst = err
                if not ok:
                    failures += 1
                    if failures <= 5:
                        print(f"  tick {t} y{i+1}: SV={sv_v} "
                              f"Py={py_v} err={err}",
                              file=sys.stderr)
        if failures:
            print(f"{args.subsystem}: {failures} tick(s) out of tolerance "
                  f"(worst {worst:.6e} > {args.tol})", file=sys.stderr)
            return 1
        print(f"{args.subsystem}: {args.ticks} ticks, worst err "
              f"{worst:.6e} (tol {args.tol})", file=sys.stderr)
        return 0


if __name__ == "__main__":
    sys.exit(main())
