#!/usr/bin/env python3
# scripts/gen_sym_stub.py — regenerate runtime/toolbox/sym/runtime_sym_stub.cpp.
#
# Parses runtime/toolbox/sym/runtime_sym.h, walks every
# `matlab_sym_*` / `matlab_symmat_*` C ABI declaration, and emits one
# dlopen forwarding stub per entry.  Used by #50 Phase 3 — see
# the file's header comment for the design.
#
# Run from the repo root:
#     python3 scripts/gen_sym_stub.py > runtime/toolbox/sym/runtime_sym_stub.cpp
import re, sys

text = open('runtime/toolbox/sym/runtime_sym.h').read()
text = re.sub(r'/\*[\s\S]*?\*/', '', text)
text = re.sub(r'//[^\n]*', '', text)

out, depth = [], 0
for ch in text:
    if ch == '(': depth += 1
    elif ch == ')': depth -= 1
    out.append(' ' if (ch == '\n' and depth > 0) else ch)
text = ''.join(out)

pat = re.compile(
    r'^([^;{}\n]*?)\b(matlab_(?:sym|symmat)_[a-z_0-9]+)\s*'
    r'\(([^)]*)\)\s*;',
    re.MULTILINE)

decls, seen = [], set()
for m in pat.finditer(text):
    ret = re.sub(r'\s+', ' ', m.group(1)).strip()
    name = m.group(2)
    if name in seen: continue
    seen.add(name)
    args = re.sub(r'\s+', ' ', m.group(3)).strip()
    decls.append((ret, name, args))

print(f"// Auto-generated by scripts/gen_sym_stub.py from runtime_sym.h", file=sys.stderr)
print(f"// {len(decls)} stub entries", file=sys.stderr)

# (the rest is the runtime stub preamble + per-decl emit — see git history)
